/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.bburnett.gsonswaggerplugin

import com.fasterxml.jackson.databind.MapperFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.json.JsonMapper
import com.google.gson.Gson
import testobjects.SimpleNameChanged
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull


class AnnotationIntrospectorTests {
    @Test
    fun basicGsonObject() {
        val pojo = SimpleNameChanged() //ExposedFields("a", "b", "c", "d");
        pojo.hello = "hello"
        val customObjectMapper = JsonMapper.builder()
            .configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true)
            .annotationIntrospector(GsonAnnotationIntrospector())
            .build()
        val jacksonJson = customObjectMapper.writeValueAsString(pojo)

        val gsonJson = Gson().toJson(pojo)
        val om = ObjectMapper()
        assertEquals(om.readTree(jacksonJson), om.readTree(gsonJson))

        val jacksonSimpleNameChanged: SimpleNameChanged = customObjectMapper.readValue(jacksonJson, SimpleNameChanged::class.java)
        val gsonSimpleNameChanged = Gson().fromJson(gsonJson, SimpleNameChanged::class.java)
        assertNotNull(jacksonSimpleNameChanged)

        assertEquals(jacksonSimpleNameChanged, gsonSimpleNameChanged)

        println("jackson: ${jacksonSimpleNameChanged.hello}")
        println("gson:    ${gsonSimpleNameChanged.hello}")
    }
}
