/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gsonswaggerplugin

import com.fasterxml.jackson.databind.MapperFeature
import com.fasterxml.jackson.databind.json.JsonMapper
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import testobjects.ExposedFields
import kotlin.test.Test


class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        val pojo = ExposedFields("a", "b", "c", "d");
        val om = JsonMapper.builder().configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true).build()
        val jacksonJson = om.writeValueAsString(pojo)
        println("jackson:     $jacksonJson")
        var gsonJson = Gson().toJson(pojo)
        println("gson:        $gsonJson")
        val gson = GsonBuilder().excludeFieldsWithoutExposeAnnotation().create()
        gsonJson = gson.toJson(pojo)
        println("gson expose: $gsonJson")
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
